version: '3'

networks:
    laravel:
        name: laravel

services:
    site:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        container_name: nginx
        ports:
            - "${NGINX_PORT:-8081}:80"
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
            - php
            - redis
        networks:
            - laravel

    mysql:
        image: mysql:8
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3307:3306"
        environment:
            MYSQL_USER: root
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        entrypoint:
            sh -c "
            echo 'CREATE DATABASE IF NOT EXISTS ${DB_DATABASE:-laravel}; CREATE DATABASE IF NOT EXISTS ${DB_DATABASE_TEST:-laravel_testing}' > /docker-entrypoint-initdb.d/init.sql;
            /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
            "
        volumes:
            - "${DB_VOLUME:-~/mysql/}:/var/lib/mysql"
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: php
        volumes:
            - ./:/var/www/html
            - "~/.config/psysh/psysh_history:/root/.config/psysh/psysh_history"
        ports:
            - "${PHP_PORT:-9001}:9000"
        networks:
            - laravel

    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - "${REDIS_PORT:-6379}:6379"
        networks:
            - laravel

    composer:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: composer
        volumes:
            - ./:/var/www/html
            - "~/.config/psysh/psysh_history:/root/.config/psysh/psysh_history"
        working_dir: /var/www/html
        depends_on:
            - php
            - mysql
            - redis
        entrypoint: [ 'composer' ]
        networks:
            - laravel

    npm:
        image: node:latest
        container_name: npm
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        entrypoint: [ 'npm' ]
        networks:
            - laravel

    artisan:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: artisan
        volumes:
            - ./:/var/www/html
            - "~/.config/psysh/psysh_history:/root/.config/psysh/psysh_history"
        depends_on:
            - php
            - mysql
            - redis
        working_dir: /var/www/html
        entrypoint: [ 'php', 'artisan' ]
        networks:
            - laravel
